### ISSUE TITLE
Error creating wishlist in group

### ISSUE THREAD

**Issue by TheToby1** [aunefyren/poenskelisten#37]
Steps to reproduce:
* Create a group
* Click into the new group
* Scroll down and try to "Create a new wishlist in this group"

What should happen:
A new list with the current user as the owner should appear.

What happens:
Error saying "Failed to parse request." will appear at the top of the page because the browser gets a 400 from the API. 

The logs contain the following line:
Failed to parse request. Error: json: cannot unmarshal number into Go struct field WishlistCreationRequest.group of type *uuid.UUID

Let me know if you need any other information.

**Comment by aunefyren** [comment]
Thank you for the detailed issue. Fixed in v2.0.8.

**Comment by TheToby1** [comment]
It doesn't seem to have worked. I'm still getting the same error.

**Comment by aunefyren** [comment]
Could it be your browser cache? Try incognito mode.

**Comment by TheToby1** [comment]
Yep, clearing the cache worked! Thanks for the quick responses.
